# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4fa36298d093558529632042437318f299da5058ac235c535229b45a207360203eac1a78e2e81ae868a14de0532b0f35353bdc59c2cf72cf71ed7ee87a89066

test:
  secret_key_base: 6c079fda4881e6a72b1660330052d70562dc479d73333a7a5fa9c6e0a56ecc775537dc691485a3d2a9953c64617caf6adf94fd547fde5de60247a8e19bb10a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
